[package]
name = "dummy-api"
version = "0.1.0"
authors = [
    "Jernej Kos <jernej@kos.mx>"
]
build = "build.rs"

[dependencies]
ekiden-core-common = { path = "../ekiden/core/common" }
protobuf = "1.4.3"

[build-dependencies]
ekiden-tools = { path = "../ekiden/tools" }

